### ISSUE TITLE
General site layout

### ISSUE THREAD

**Issue by BDen32** [BDen32/love-running#10]
As a site visitor (new or already a member), I want to be able to easily navigate throughout the site.  

**Acceptance Criteria:**

- [x] The homepage is clear with a header, footer and sections in between. 
- [x] The navbar is responsive and links go to correct pages.
- [x] The site is responsive and looks good on all main device sizes.

**Tasks:**

- [x] Add a Bootstrap navbar to the homepage HTML section.
- [x] Make nav bar links go to correct pages
- [x] Add relevant sections to the homepage
- [x] Add footer that is responsive
