### ISSUE TITLE
LLVAA Club Info

### ISSUE THREAD

**Issue by BDen32** [BDen32/love-running#11]
**User story**:
As a potential new member, I want to find relevant content about the club including health and wellbeing benefits  

**Acceptance Criteria:**

- [x] The navbar displays an About Us link
- [x] The About Us page includes information about the club in general
- [ ] #14
- [x] The page is responsive and looks good on all main device sizes.

**Tasks:**

- [x] Add a new HTML page for About Us
- [x] Add link to navbar
- [x] Add HTML section for About Us info
- [ ] #13
