### ISSUE TITLE
Gallery page

### ISSUE THREAD

**Issue by BDen32** [BDen32/love-running#12]
**User Story**: As a potential new member I want to see photos of fish, the river, environment etc to help me decide to join/sign up.

**Acceptance Criteria:**

- [x] The navbar displays a link to the gallery page
- [x] The gallery page contains a number of images that are relevant
- [ ] The gallery is responsive and looks good on all main device sizes.

**Tasks**

- [x] Add a HTML page for the gallery
- [x] Add a link to the navbar
- [x] Add images that are high quality
- [x] Style the gallery to be responsive on all screen sizes
